/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



//import de.javasoft.plaf.synthetica.SyntheticaStandardLookAndFeel;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author GaUrAv
 */
public class ok extends javax.swing.JFrame {

    /**
     * Creates new form ok
     */
    Graphics g;
    
    public ok() {
        //setSize(900,700);
        Dimension  d1=Toolkit.getDefaultToolkit().getScreenSize();
        setSize(d1);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Java UML Generator");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(1370, 768));
        setResizable(false);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField1.setBorder(null);
        jTextField1.setMaximumSize(new java.awt.Dimension(100, 18));
        jTextField1.setMinimumSize(new java.awt.Dimension(100, 18));
        jTextField1.setPreferredSize(new java.awt.Dimension(100, 18));

        jButton1.setBackground(java.awt.Color.gray);
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 204, 255));
        jButton1.setText("OPEN");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton2.setBackground(java.awt.Color.darkGray);
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 153, 255));
        jButton2.setText("CAPTURE");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 3, 11)); // NOI18N
        jLabel1.setForeground(java.awt.Color.darkGray);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juggy1.jpg"))); // NOI18N
        jLabel1.setText("JUG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try
       {
           this.repaint();
        JFileChooser jjjj=new JFileChooser();
        FileFilter filter = new FileNameExtensionFilter("JAVA FILES","java");
        jjjj.setFileFilter(filter);
      
        jjjj.showOpenDialog(new JTable());
        File f1=jjjj.getSelectedFile();
        String ssss=f1.getAbsolutePath();
        jTextField1.setText(ssss);
        
        FileInputStream fis=new FileInputStream(f1);
        InputStreamReader is=new InputStreamReader(fis);
        BufferedReader br=new BufferedReader(is);
        String c;
        
        String s[]=new String [1000];
        String f[][]=new String[20][20];
        String y[][]=new String[10][10];
        int z=0,p=-1,q=0,pp=-1,qq=0,rr=0,ff=0;
    
        String t[]=new String [50];
        int vv[][]=new int[10][1];
        int mt[][]=new int[10][1];
        String m1=br.readLine();
        int count=0,var=0,mth=0;
        for(int i=0;m1!=null;i++)
        {
            m1=m1.trim();
            s[i]=m1;
            m1=br.readLine();
            rr++;
        }
        for(int i=0;i<rr;i++)
        {
            c = null;
            String b=s[i];
            while(b!=null)
            {
                int m=b.indexOf(' ');
                if(m!=-1)
                {
                    c=b.substring(0,m);
                    b=b.substring(m+1);
                 }
                else if(m==-1)
                {
                    c=b;
                    b=null;
                 }
                // for single line coment
                if(c.startsWith("//"))
                  break;
             //for multiline comment
                 if(s[i].startsWith("/*"))
                {
                    while(s[i].endsWith("*/"))
                        i++;
                    break;
                }
                if(c.equals("class")||c.equals("int")||c.equals("new")||c.equals("{")||c.equals("}")||c.equals("=new")||c.endsWith("new"))
                {
                   t[z++]=s[i];
                   break;
                }
            }
       }
        //Printing the array
        for(int i=0;i<z;i++)
        {
            System.out.println(t[i]);
        }
        //Now cheking the keywords individually
        for(int i=0;i<z;i++)
        {
            String word;            
            String b=t[i];          //b=class demo extends two
            while(b!=null)
            {
                int m=b.indexOf(' ');//m=5
                if(m!=-1)
                {
                    c=b.substring(0,m);//c=class
                    b=b.substring(m+1);//b=demo extends two
                 }
                else
                {
                    c=b;
                    b=null;
                }
               if(c.equals("class"))
                {
                    ff++;//ff=1
                     p++;//p=0
                     pp++;//pp=0
                    q=0;
                    qq=0;
                    mth=0;
                    var=0;
                    count++;//count=1
                    int n=b.indexOf(' ');//n=4
                 //  int n=m;
                   //String o=t[i];
                   String o=b;//o=demo extends two
                   int u=0;
                   while(true)
                   {
                       //o=o.substring(n+1);//o=extends two
                       //n=o.indexOf(' ');
                       if(n==-1)
                       {
                           n=o.length();//n=3
                         u=n;
                           word=o.substring(0,n);
                           //n=-1;
                       }
                       else
                        word=o.substring(0,n);//word=extends
                       f[p][q++]=word;//f[0][0]=extends
                       if(q-1==0)
                       y[pp][qq++]=word;//y[pp][qq]=demo
                       
                       System.out.println("CLASS :"+word);//extends
                       if(n==u)
                             break; 
                       o=o.substring(n+1);//two
                        n=o.indexOf(' ');//n=-1
                        
                         
                   }
                   break;
                }
                else if(c.equals("int"))
                {
                    if(b.endsWith(")"))
                    {
                       
                        int n=b.indexOf(')');
                        String name=b.substring(0,n+1);
                        f[p][q++]=name;
                        y[pp][qq++]=name;
                        mt[p][0]= ++mth;
                        System.out.println("function : "+name);
                    }
                    else if(!b.endsWith(");"))
                    {
                        
                        int k=b.indexOf(',');
                        int j=0;
                         String m2=b;
                         while(k!=-1)
                         {
                             String name=m2.substring(0,k);
                             f[p][q++]=name;
                             y[pp][qq++]=name;
                             vv[p][0]=++var;
                             System.out.println("Variable : "+name);
                             j=0;
                             m2=m2.substring(k+1);
                             k=m2.indexOf(',');
                         }
                         if(k==-1)
                         {
                             k=m2.indexOf('=');
                             if(k==-1)
                             k=m2.indexOf(';');      
                             String name=m2.substring(0,k);
                             f[p][q++]=name;
                             y[pp][qq++]=name;
                             vv[p][0]=++var;
                         }
                    }
                }
                else if((c.equals("new")||c.equals("=new")||c.endsWith("new")))
                {
                    int jj=t[i].indexOf("new");
                    int k=t[i].indexOf('(');
                    String name=t[i].substring(jj+4,k);
                    System.out.println("OBJECT: "+name);
                    f[p][q++]=name;
                   
                }
                    
                 }
             }
       /* int fo=0;
          String g[]=new String [100];*/
        System.out.print("\nPRINTING THE @D ARRAY");
        for(int i=0;i<ff;i++)
        {
            System.out.println();
            for(int j=0;j<f[i].length;j++)
            {
                if(f[i][j]!=null)
                {
                System.out.print(f[i][j]+" ");
           // g[fo]=f[i][j];
           // fo++;
                }
                    
            
             }
        }
        
        
        System.out.print("\n\nPRINTING THE only ARRAY");
        for(int i=0;i<ff;i++)
        {
            System.out.println();
            for(int j=0;j<y[i].length;j++)
            {
                if(y[i][j]!=null)
                {
                System.out.print(y[i][j]+" ");
           // g[fo]=f[i][j];
           // fo++;
                }
                    
            
             }
        }
        System.out.println("\n\nNO OF METHODS");
        for(int i=0;i<ff;i++)
            System.out.print(mt[i][0]+" ");
        System.out.println("\n\nNO OF variables");
        for(int i=0;i<ff;i++)
            System.out.print(vv[i][0]+" ");
     
        //System.out.println(" CLass: "+count+" Method: "+ mth+" Variable: "+var);
        g = getGraphics();
        int ddd;
        int i=p+1;
        Font ff4;
           ff4 = new Font("TimesNewRoman",Font.BOLD,20);
        g.setFont(ff4);
        int cc=0;
        //int gap=var*30;
        if(i==1)
        {
            int gap = vv[0][0]*30;
            int fgap=mt[0][0]*30;
              cc=0;
            g.drawString(y[0][0],540,120);
            g.drawLine(300, 130, 800, 130);
          ddd=130;
                for(int zz=1;zz<y[0].length&&y[0][zz]!=null;zz++)
                {
                    if(!y[0][zz].endsWith(")"))
                    {
                       cc++;
                        g.drawString(y[0][zz], 310, ddd+=20);
                    } 
                }
                if(cc==0)
                    g.drawLine(300, ddd, 800, ddd);
                else
                { g.drawLine(300, ddd+10, 800, ddd+10);
           ddd+=10;}
                cc=0;
            for(int zz=1;zz<y[0].length&&y[0][zz]!=null;zz++)
                {
                    if(y[0][zz].endsWith(")"))
                    {
                        cc++;
                        g.drawString(y[0][zz], 310, ddd+=20);
                    } 
                }    
            if(cc==0)
            {
                g.drawRect(300, 100, 500, ddd-100);    
            
            }
            else
            g.drawRect(300, 100, 500, ddd-100+10);    
            
            
        }
        else if(i==2)
        {
            int gap = vv[0][0]*30;
            int fgap = mt[0][0]*30;
            cc=0;
            g.drawString(y[0][0],380,120);
        //Relationship
      //    g.drawLine(600,110,750,110);// for 2nd to 1st
            
            g.drawLine(200, 130, 600, 130);
            ddd=130;
                for(int zz=1;zz<y[0].length&&y[0][zz]!=null;zz++)
                {
                    if(!y[0][zz].endsWith(")"))
                    {
                        cc++;
                        g.drawString(y[0][zz], 210, ddd+=20);
                    } 
                }
           //     g.drawLine(200,ddd+gap,800,ddd+gap);
               if(cc==0)
                   g.drawLine(200, ddd, 800, ddd);
               else
               {g.drawLine(200, ddd+10, 600, ddd+10);
            ddd+=10;}
            cc=0;
                for(int zz=1;zz<y[0].length&&y[0][zz]!=null;zz++)
                {
                    if(y[0][zz].endsWith(")"))
                    {
                         cc++;
                        g.drawString(y[0][zz], 210, ddd+=20);
                    } 
                }
           //     g.drawRect(200,100,400, ddd+fgap-100);
              if(cc==0) 
            g.drawRect(200, 100, 400, ddd-100);
               else
                   g.drawRect(200, 100, 400, ddd-100+10);   
            
            
             gap = vv[1][0]*30;
            fgap = mt[1][0]*30;
            g.drawString(y[1][0],930,120);
            //Relationship
         //   g.drawLine(750, 123,600,123);//for 1st to 2nd
            
            g.drawLine(750, 130, 1150, 130);
            ddd=130;
            cc=0;
    for(int zz=1;zz<y[1].length&&y[1][zz]!=null;zz++)
                {
                    if(!y[1][zz].endsWith(")"))
                    {
                        cc++;
                        g.drawString(y[1][zz], 760, ddd+=20);
                    } 
                }
    if(cc==0)
        g.drawLine(750, ddd, 1150, ddd);
    else
    { g.drawLine(750, ddd+10, 1150, ddd+10);
    ddd+=10;}
            cc=0;
    for(int zz=1;zz<y[1].length&&y[1][zz]!=null;zz++)
                {
                    if(y[1][zz].endsWith(")"))
                    {
                        cc++;
                        g.drawString(y[1][zz], 760, ddd+=20);
                    } 
                }
    if(cc==0)
        g.drawRect(750, 100, 400, ddd-100);
    else            
     g.drawRect(750,100, 400, ddd-100+10);
            for(int jj=0;jj<ff;jj++)
            {
                for(int k=1;k<f[jj].length&&f[jj][k]!=null;k++)
                {
                    System.out.println("\n\nWORD = "+f[jj][k]);
                    if(f[jj][k].equals(f[0][0])||f[jj][k].equals(f[1][0]))//finds equal class name
                    {
                        System.out.println("check = "+f[jj][k]);
                        if(jj==0)
                        {
                            
                            if(f[jj][k].equals(f[1][0]))
                            {
                                System.out.println("Draw = "+f[jj][k]);
                                g.drawLine(600,110,750,110);// for 2st to 2nd
                                if(f[jj][k-1].equals("extends"))
                                {
                                    g.drawLine(740,100,750,110);
                                    g.drawLine(740,120,750,110);
                                }
                                else
                                {
                                    int x[]={740,750,740};
                                    int yy[]={100,110,120};
                                            
                                    g.fillPolygon(x, yy,3);
                                }
                                    
                            }
                        }
                        if(jj==1)
                        {
                            
                            if(f[jj][k].equals(f[0][0]))
                            {
                                System.out.println("draw = "+f[jj][k]);
                                g.drawLine(750, 123,600,123);//for 2nd to 1st
                                if(f[jj][k-1].equals("extends"))
                                {
                                    g.drawLine(610,113,600,123);
                                    g.drawLine(610,133,600,123);
                                }
                                else
                                {
                                    int x[]={610,600,610};
                                    int yy[]={113,123,133};
                                            
                                    g.fillPolygon(x, yy,3);
                                }
                            }
                        }
   
                        
                    }
                }
            }
       
        }
        else if(i==3)
        {
            
            int gap = vv[0][0]*30;//gap=90
             int fgap = mt[0][0]*30;//gap=90
          cc=0;
            g.drawString(y[0][0], 190, 220);
            //relationship
           g.drawLine(300, 223,500,223);//1 se 2
            g.drawLine(500,223,500,70);//1 se 2
            g.drawLine(500,70,600,70);//1 se 2
         //  g.drawLine(300,260,1100,260);//1 se 3
            // g.drawLine(1100,275,300,275);//3 se 1
            
            g.drawLine(100, 230, 300, 230);
            ddd=230;
            for(int zz=1;zz<y[0].length&&y[0][zz]!=null;zz++)
                {
                    if(!y[0][zz].endsWith(")"))
                    {
                        cc++;
                        g.drawString(y[0][zz], 110, ddd+=20);
                    } 
                }
                if(cc==0)
                    g.drawLine(100, ddd, 300, ddd);
                else
                { g.drawLine(100, ddd+10, 300, ddd+10);
                ddd+=10;}
                cc=0;
                for(int zz=1;zz<y[0].length&&y[0][zz]!=null;zz++)
                {
                    if(y[0][zz].endsWith(")"))
                    {
                        cc++;
                        g.drawString(y[0][zz], 110, ddd+=20);
                    } 
                }
                if(cc==0)
                    g.drawRect(100, 200, 200, ddd-200);    
                    else
            g.drawRect(100, 200, 200, ddd+10-200);
            

             gap = vv[1][0]*30;
            fgap = mt[1][0]*30;
            cc=0;
            g.drawString(y[1][0], 690, 70);
            //relationship
           /* g.drawLine(600, 60,200,60);//2 se 1
            g.drawLine(200,60,200,200);//2 se 1*/
          //  g.drawLine(800,60,1200,60);//2 se 3
            //g.drawLine(1200, 60, 1200, 250);//2 se 3

            g.drawLine(600, 80, 800, 80);
            ddd=80;
            for(int zz=1;zz<y[1].length&&y[1][zz]!=null;zz++)
                {
                    if(!y[0][zz].endsWith(")"))
                    {
                        cc++;
                        g.drawString(y[0][zz], 610, ddd+=20);
                    } 
                }
            if(cc==0)
                g.drawLine(600, ddd, 800, ddd);
            else
            {g.drawLine(600, ddd+10, 800, ddd+10);
            ddd+=10;}
            cc=0;
              for(int zz=1;zz<y[1].length&&y[1][zz]!=null;zz++)
                {
                    if(y[0][zz].endsWith(")"))
                    {
                        cc++;
                        g.drawString(y[0][zz], 610, ddd+=20);
                    } 
                }
              if(cc==0)
                  g.drawRect(600, 50, 200, ddd-50);    
            else
                 g.drawRect(600, 50, 200, ddd-50+10);
                         
            gap = vv[2][0]*30;
             fgap = mt[2][0]*30;
            cc=0;
             g.drawString(y[2][0], 1190, 270);
           // relationship
        /*    g.drawLine(1100,275,300,275);//4 se 1
            g.drawLine(1180,250,1180,80);//3 se 2
            g.drawLine(1180,80,800,80);//3 se 2*/
             
             g.drawLine(1100, 280, 1300, 280);
            ddd=280;
          
                for(int zz=1;zz<y[2].length&&y[2][zz]!=null;zz++)
                {
                    if(!y[0][zz].endsWith(")"))
                    {
                        cc++;
                        g.drawString(y[0][zz], 1110, ddd+=20);
                    } 
                }
            
             if(cc==0)
                 g.drawLine(1100, ddd, 1300, ddd);
             else
             {g.drawLine(1100, ddd+10, 1300, ddd+10);
            ddd+=10;}
             cc=0;
        for(int zz=1;zz<y[2].length&&y[2][zz]!=null;zz++)
                {
                    if(y[0][zz].endsWith(")"))
                    {
                        cc++;
                        g.drawString(y[0][zz], 1110, ddd+=20);
                    } 
                }
        if(cc==0)
            g.drawRect(1100, 250, 200, ddd-250);    
            else
             g.drawRect(1100, 250, 200, ddd-250+10);
             
             
              for(int jj=0;jj<ff;jj++)
            {
                for(int k=1;k<f[jj].length&&f[jj][k]!=null;k++)
                {
                    System.out.println("\n\nWORD = "+f[jj][k]);
                    if(f[jj][k].equals(f[0][0])||f[jj][k].equals(f[1][0])||f[jj][k].equals(f[2][0]))//finds equal class name
                    {
                        System.out.println("check = "+f[jj][k]);
                        if(jj==0)
                        {
                            
                            if(f[jj][k].equals(f[1][0]))
                            {
                                     g.drawLine(300, 223,500,223);//1 se 2
                                     g.drawLine(500,223,500,70);//1 se 2
                                     g.drawLine(500,70,600,70);//1 se 2
                                  if(f[jj][k-1].equals("extends"))
                                {
                                    System.out.println("draw = "+f[jj][k]);
                                    g.drawLine(590,60,600,70);
                                    g.drawLine(590,80,600,70);
                                }
                                else
                                {
                                    int x[]={590,600,590};
                                    int yy[]={60,70,80};
                                            
                                    g.fillPolygon(x, yy,3);
                                }
                            }
                        
                     
                           if(f[jj][k].equals(f[2][0]))
                            {
                                  g.drawLine(300,260,1100,260);//1 se 3
                                  if(f[jj][k-1].equals("extends"))
                                {
                                    g.drawLine(1000,250,1100,260);
                                    g.drawLine(1200,250,1100,260);
                                }
                                else
                                {
                                    int x[]={1000,1100,1200};
                                    int yy[]={250,260,250};
                                            
                                    g.fillPolygon(x, yy,3);
                                }
                            }
                        }
                        if(jj==1)
                        {
                            
                            if(f[jj][k].equals(f[0][0]))
                            {
                                     g.drawLine(600, 60,200,60);//2 se 1
                                     g.drawLine(200,60,200,200);//2 se 1
                                     if(f[jj][k-1].equals("extends"))
                                {
                                    g.drawLine(190,190,200,200);
                                    g.drawLine(210,190,200,200);
                                }
                                else
                                {
                                    int x[]={190,200,210};
                                    int yy[]={190,200,190};
                                            
                                    g.fillPolygon(x, yy,3);
                                }
                            }
                             if(f[jj][k].equals(f[2][0]))
                            {
                                   g.drawLine(800,60,1200,60);//2 se 3
                                   g.drawLine(1200, 60, 1200, 250);//2 se 3
                                         if(f[jj][k-1].equals("extends"))
                                {
                                    g.drawLine(1190,240,1200,250);
                                    g.drawLine(1210,240,1200,250);
                                }
                                else
                                {
                                    int x[]={1190,1200,1210};
                                    int yy[]={240,250,240};
                                            
                                    g.fillPolygon(x, yy,3);
                                }
                            }
                        }
                        if(jj==2)
                        {
                            
                            if(f[jj][k].equals(f[0][0]))
                            {
                                     g.drawLine(1100,275,300,275);//3 se 1
                                         if(f[jj][k-1].equals("extends"))
                                {
                                    g.drawLine(310,265,300,275);
                                    g.drawLine(310,285,300,275);
                                }
                                else
                                {
                                    int x[]={310,300,310};
                                    int yy[]={265,275,285};
                                            
                                    g.fillPolygon(x, yy,3);
                                }
                            }
                             if(f[jj][k].equals(f[1][0]))
                            {
                                  g.drawLine(1180,250,1180,80);//3 se 2
                                  g.drawLine(1180,80,800,80);//3 se 2
                                      if(f[jj][k-1].equals("extends"))
                                {
                                    g.drawLine(810,70,800,80);
                                    g.drawLine(810,90,800,80);
                                }
                                else
                                {
                                    int x[]={810,800,810};
                                    int yy[]={70,80,90};
                                            
                                    g.fillPolygon(x, yy,3);
                                }
                            }
                        }
   
                        
                    }
                }
            }
            
        }
        else if(i==4)
        {
              int gap = vv[0][0]*30;
              int fgap = mt[0][0]*30;
              cc=0;
              g.drawString(y[0][0],280,420);
                       
              g.drawLine(200, 430, 400, 430);
              ddd=430;
            
                for(int zz=1;zz<y[0].length&&y[0][zz]!=null;zz++)
                {
                    if(!y[0][zz].endsWith(")"))
                    {
                        cc++;
                        g.drawString(y[0][zz], 210, ddd+=20);
                    } 
                }
                if(cc==0)
                    g.drawLine(200, ddd, 400, ddd);
                else
                {g.drawLine(200, ddd+10, 400, ddd+10);
                 ddd+=10;}
                cc=0;

                for(int zz=1;zz<y[0].length&&y[0][zz]!=null;zz++)
                {
                    if(y[0][zz].endsWith(")"))
                    {
                        cc++;
                        g.drawString(y[0][zz], 210, ddd+=20);
                    } 
                }
                if(cc==0)
                    g.drawRect(200, 400, 200, ddd-400);    
            else
                g.drawRect(200, 400, 200, ddd+10-400);
              
                gap = vv[1][0]*30;
              fgap = mt[1][0]*30;
            cc=0;
              g.drawString(y[1][0],280,70);
            //relationship
           /*   g.drawLine(400,60,700,60);//2 se 3
              
              g.drawLine(700 ,80,400,80 );//3 se 2*/
              
                                 
             
              g.drawLine(200, 80, 400, 80);
            ddd=80;
           int tO1=ddd;
            
            for(int zz=1;zz<y[1].length&&y[1][zz]!=null;zz++)
                {
                    if(!y[1][zz].endsWith(")"))
                    {
                        cc++;
                        g.drawString(y[1][zz], 210, ddd+=20);
                    } 
                }
            if(cc==0)
                g.drawLine(200, ddd, 400, ddd);
            else
            {g.drawLine(200, ddd+10, 400, ddd+10);
            ddd+=10;}
            //relation
            int tO31=ddd,tO32=ddd-20,tO33=ddd+20,tO34,tO2;
         /*  g.drawLine(400,tO31,760,400);//2 se 4
            
           g.drawLine(400,tO32,780,400);//4 se 2*/
        /*  g.drawLine(350,400, 700,ddd);//1 se 3
      
          g.drawLine( 700,ddd+20,350+20,400);//3 se 1*/
          
            cc=0;
            for(int zz=1;zz<y[1].length&&y[1][zz]!=null;zz++)
                {
                    if(y[1][zz].endsWith(")"))
                    {
                        cc++;
                        g.drawString(y[1][zz], 210, ddd+=20);
                    } 
                }
            if(cc==0)
            {      g.drawRect(200, 50, 200, ddd-50);  tO2 =ddd;} 
            else
            {  g.drawRect(200, 50, 200, ddd+10-50);tO2=ddd+10;}
            //relationship
            tO1=ddd+10;
          //  int tO2=ddd+10;
        /*     g.drawLine(350,400, 700,tO2);//1 se 3
      
          g.drawLine( 700,tO2,350+20,400);//3 se 1*/

        /*    g.drawLine(280,tO1,280,400);//1 se 2
            g.drawLine(320,tO1,320,400);//2 se 1*/
            
            
            gap = vv[2][0]*30;
            fgap = mt[2][0]*30;
            cc=0;
            g.drawString(y[2][0],780,420);
            //relationship
          /*  g.drawLine(700,410,400,410);//4 se 1
           g.drawLine(400, 430-10,700, 430-10);//1 se 4*/
          
            g.drawLine(700, 430, 900, 430);
            ddd=430;
            
            for(int zz=1;zz<y[2].length&&y[2][zz]!=null;zz++)
                {
                    if(!y[2][zz].endsWith(")"))
                    {
                        cc++;
                        g.drawString(y[2][zz], 710, ddd+=20);
                    } 
                }
            if(cc==0)
                g.drawLine(700, ddd, 900, ddd);
            else
            {g.drawLine(700, ddd+10, 900, ddd+10);
            ddd+=10;
            }
            cc=0;
            for(int zz=1;zz<y[2].length&&y[2][zz]!=null;zz++)
                {
                    if(y[2][zz].endsWith(")"))
                    {
                        cc++;
                        g.drawString(y[2][zz], 710, ddd+=20);
                    } 
                }
            if(cc==0)
            { g.drawRect(700, 400, 200, ddd-400);   tO2=ddd-400;} 
            else
            {  g.drawRect(700, 400, 200, ddd+10-400);tO2=ddd+10-400;}
               // tO2=ddd-400+10;
          /*   g.drawLine(350,400, 700,tO2-10);//1 se 3
      
          g.drawLine( 700,tO2,350+20,400);//3 se 1*/

            
       
            gap = vv[3][0]*30;
            fgap = mt[3][0]*30;
            cc=0;
            g.drawString(y[3][0],780,70);
                     
            g.drawLine(700, 80, 900, 80);
            ddd=80;
            
            for(int zz=1;zz<y[3].length&&y[3][zz]!=null;zz++)
                {
                    if(!y[3][zz].endsWith(")"))
                    {
                        cc++;
                        g.drawString(y[3][zz], 710, ddd+=20);
                    } 
                }
            if(cc==0)
                g.drawLine(700, ddd, 900, ddd);
            else
            {g.drawLine(700, ddd+10, 900, ddd+10);
            ddd+=10;}
            cc=0;
         for(int zz=1;zz<y[3].length&&y[3][zz]!=null;zz++)
                {
                    if(y[3][zz].endsWith(")"))
                    {
                        cc++;
                        g.drawString(y[3][zz], 710, ddd+=20);
                    } 
                }
         if(cc==0)
             g.drawRect(700, 50, 200, ddd-50);    
            else
            g.drawRect(700, 50, 200,ddd+10-50);
            
            //relation
            int tO41=ddd+10;
        /*    g.drawLine(780,tO41,780,400);//3 se 4
            g.drawLine(820,tO41,820,400);//4 se 3*/
            
             for(int jj=0;jj<ff;jj++)
            {
                for(int k=1;k<f[jj].length&&f[jj][k]!=null;k++)
                {
                    System.out.println("\n\nWORD = "+f[jj][k]);
                    if(f[jj][k].equals(f[0][0])||f[jj][k].equals(f[1][0])||f[jj][k].equals(f[2][0])||f[jj][k].equals(f[3][0]))//finds equal class name
                    {
                        System.out.println("check = "+f[jj][k]);
                        if(jj==0)
                        {
                            
                            if(f[jj][k].equals(f[1][0]))
                            {
                                  g.drawLine(280,tO1,280,400);//1 se 2
  
                                if(f[jj][k-1].equals("extends"))
                                {
                                    System.out.println("draw = "+f[jj][k]);
                                    g.drawLine(270,tO1+10,280,tO1);
                                    g.drawLine(290,tO1+10,280,tO1);
                                }
                                else
                                {
                                    int x[]={270,280,290};
                                    int yy[]={tO1+10,tO1,tO1+10};
                                            
                                    g.fillPolygon(x, yy,3);
                                }
                            }
                            if(f[jj][k].equals(f[2][0]))
                            {
                                   g.drawLine(350+20,400, 700,tO2-10);//1 se 3
        
                                  if(f[jj][k-1].equals("extends"))
                                {
                                    g.drawLine(680,tO2-10,700,tO2-10);
                                    g.drawLine(690,tO2+10,700,tO2-10);
                                }
                                else
                                {
                                    int x[]={680,700,690};
                                    int yy[]={tO2-10,tO2-10,tO2+10};
                                            
                                    g.fillPolygon(x, yy,3);
                                }
                            }
                            if(f[jj][k].equals(f[3][0]))
                            {
                                g.drawLine(400, 430-10,700, 430-10);//1 se 4
        
                                  if(f[jj][k-1].equals("extends"))
                                {
                                    g.drawLine(690,430-20,700,430-10);
                                    g.drawLine(690,430,700,430-10);
                                }
                                else
                                {
                                    int x[]={690,700,690};
                                    int yy[]={430-20,430-10,430};
                                            
                                    g.fillPolygon(x, yy,3);
                                }
                            }
                        }
                        if(jj==1)
                        {
                            
                            if(f[jj][k].equals(f[0][0]))
                            {
                                 g.drawLine(320,tO1,320,400);//2 se 1
          
                                if(f[jj][k-1].equals("extends"))
                                {
                                    g.drawLine(310,390,320,400);
                                    g.drawLine(330,390,320,400);
                                }
                                else
                                {
                                    int x[]={310,320,330};
                                    int yy[]={390,400,390};
                                            
                                    g.fillPolygon(x, yy,3);
                                }
                            }
                               if(f[jj][k].equals(f[2][0]))
                            {
                                  g.drawLine(400,60,700,60);//2 se 3
                                  System.out.println("chaman 2 to 3");
                                 if(f[jj][k-1].equals("extends"))
                                {
                                    System.out.println("chaman 2 to 3");
                                    g.drawLine(690,50,700,60);
                                    g.drawLine(690,70,700,60);
                                }
                                else
                                {
                                    //System.out.println("chaman 2 to 3");
                                    int x[]={690,700,690};
                                    int yy[]={50,60,70};
                                            
                                    g.fillPolygon(x,yy,3);
                                }
              
                            }
                            if(f[jj][k].equals(f[3][0]))
                            {
                                g.drawLine(400,tO31,760,400);//2 se 4
                                 if(f[jj][k-1].equals("extends"))
                                {
                                    g.drawLine(730,390,760,400);
                                    g.drawLine(765,390,760,400);
                                }
                                else
                                {
                                    int x[]={730,760,765};
                                    int yy[]={390,400,390};
                                            
                                    g.fillPolygon(x, yy,3);
                                }
              
                            }
                        
                        }
                        if(jj==2)
                        {
                            
                            if(f[jj][k].equals(f[0][0]))
                            {
                                  g.drawLine( 700,tO2,350+20,400);//3 se 1*/
                                if(f[jj][k-1].equals("extends"))
                                {
                                    g.drawLine(370,390,370,400);
                                    g.drawLine(390,395,370,400);
                                }
                                else
                                {
                                    int x[]={370,370,390};
                                    int yy[]={390,400,395};
                                            
                                    g.fillPolygon(x, yy,3);
                                }
                            }
                               if(f[jj][k].equals(f[1][0]))
                            {
                                   g.drawLine(700 ,80,400,80 );//3 se 2*/
                                  System.out.println("chaman 3 to 2");
                                 if(f[jj][k-1].equals("extends"))
                                {
                                    System.out.println("chaman 3 to 2");
                                    g.drawLine(410,70,400,80);
                                    g.drawLine(410,90,400,80);
                                }
                                else
                                {
                                    //System.out.println("chaman 2 to 3");
                                    int x[]={410,400,410};
                                    int yy[]={70,80,90};
                                            
                                    g.fillPolygon(x,yy,3);
                                }
              
                            }
                            if(f[jj][k].equals(f[3][0]))
                            {
                                g.drawLine(780,tO41,780,400);//3 se 4
                                if(f[jj][k-1].equals("extends"))
                                {
                                    g.drawLine(770,390,780,400);
                                    g.drawLine(770,410,780,400);
                                }
                                else
                                {
                                    int x[]={770,780,790};
                                    int yy[]={390,400,390};
                                            
                                    g.fillPolygon(x, yy,3);
                                }
              
                            }
                        
                        }
                        if(jj==3)
                        {
                            
                            if(f[jj][k].equals(f[0][0]))
                            {
                                g.drawLine(700,410,400,410);//4 se 1     
                                if(f[jj][k-1].equals("extends"))
                                {
                                    g.drawLine(410,400,400,410);
                                    g.drawLine(410,420,400,410);
                                }
                                else
                                {
                                    int x[]={410,400,410};
                                    int yy[]={400,410,420};
                                            
                                    g.fillPolygon(x, yy,3);
                                }
                            }
                            if(f[jj][k].equals(f[1][0]))
                            {
                                   g.drawLine(780,400,400,tO32);//4 se 2
                                      if(f[jj][k-1].equals("extends"))
                                {
                                    g.drawLine(400+10,tO32-5,400,tO32);
                                    g.drawLine(400+5,tO32+20,400,tO32);
                                }
                                else
                                {
                                    int x[]={400+10,400,400+5};
                                    int yy[]={tO32-5,tO32,tO32+20};
                                            
                                    g.fillPolygon(x, yy,3);
                                }
                            }
                             if(f[jj][k].equals(f[2][0]))
                            {
                                g.drawLine(820,tO41,820,400);//4 se 3
               
                                if(f[jj][k-1].equals("extends"))
                                {
                                    g.drawLine(810,tO41+10,820,tO41);
                                    g.drawLine(830,tO41+10,820,tO41);
                                }
                                else
                                {
                                    int x[]={810,820,830};
                                    int yy[]={tO41+10,tO41,tO41+10};
                                            
                                    g.fillPolygon(x, yy,3);
                                }
                            }
                        }
   
                        
                    }
                }
            }
        }
      /*  else if(i==5)
        {
              int gap = vv[0][0]*30;
              int fgap = mt[0][0]*30;
              cc=0;
              g.drawString(y[0][0],280,420);
            g.drawLine(200, 430, 400, 430);
           ddd=430;
           
            for(int zz=1;zz<y[0].length&&y[0][zz]!=null;zz++)
                {
                    if(!y[0][zz].endsWith(")"))
                    {
                        cc++;
                        g.drawString(y[0][zz], 210, ddd+=20);
                    } 
                }
            if(cc==0)
                g.drawLine(200, ddd, 400, ddd);
            else
            { g.drawLine(200, ddd+10, 400, ddd+10);
            ddd+=10;}
            cc=0;
            for(int zz=1;zz<y[0].length&&y[0][zz]!=null;zz++)
                {
                    if(y[0][zz].endsWith(")"))
                    {
                        cc++;
                        g.drawString(y[0][zz], 210, ddd+=20);
                    } 
                }
            if(cc==0)
                g.drawRect(200, 400, 200, ddd-400);    
            else
            g.drawRect(200, 400, 200, ddd-400+10);
            
            gap = vv[1][0]*30;
            fgap = mt[1][0]*30;
             cc=0;
            g.drawString(y[1][0],280,70);
            g.drawLine(200, 80, 400, 80);
            ddd=80;
            
            for(int zz=1;zz<y[1].length&&y[1][zz]!=null;zz++)
                {
                    if(!y[1][zz].endsWith(")"))
                    {
                        cc++;
                        g.drawString(y[1][zz], 210, ddd+=20);
                    } 
                }
            if(cc==0)
                g.drawLine(200, ddd, 400, ddd);
            else
            {g.drawLine(200, ddd+10, 400, ddd+10);
            ddd+=10;}
            cc=0;
            for(int zz=1;zz<y[1].length&&y[1][zz]!=null;zz++)
                {
                    if(y[1][zz].endsWith(")"))
                    {
                        cc++;
                        g.drawString(y[1][zz], 210, ddd+=20);
                    } 
                }
            if(cc==0)
                g.drawRect(200, 50, 200, ddd-50);    
            else
         g.drawRect(200, 50, 200,ddd-50+10);
            
            gap = vv[2][0]*30;
            fgap = mt[2][0]*30;
            cc=0;
            g.drawString(y[2][0],980,420);
            g.drawLine(900, 430, 1100, 430);
            ddd=430;
           
            for(int zz=1;zz<y[2].length&&y[2][zz]!=null;zz++)
                {
                    if(!y[2][zz].endsWith(")"))
                    {
                        cc++;
                        g.drawString(y[2][zz], 910, ddd+=20);
                    } 
                }
            if(cc==0)
                g.drawLine(900, ddd, 1100, ddd);
            else
            {g.drawLine(900, ddd+10, 1100, ddd+10);
            ddd+=10;}
            cc=0;
               for(int zz=1;zz<y[2].length&&y[2][zz]!=null;zz++)
                {
                    if(y[2][zz].endsWith(")"))
                    {
                        cc++;
                        g.drawString(y[2][zz], 910, ddd+=20);
                    } 
                }
               if(cc==0)
                   g.drawRect(900, 400, 200, ddd-400);    
            else
           g.drawRect(900, 400, 200, ddd-400+10);
            
            gap = vv[3][0]*30;
            fgap = mt[3][0]*30;
            cc=0;
            g.drawString(y[3][0],980,70);
            g.drawLine(900, 80, 1100, 80);
           ddd=80;
          
            for(int zz=1;zz<y[3].length&&y[3][zz]!=null;zz++)
                {
                    if(!y[3][zz].endsWith(")"))
                    {
                        cc++;
                        g.drawString(y[3][zz], 910, ddd+=20);
                    } 
                }
            if(cc==0)
                g.drawLine(900, ddd, 1100, ddd);
            else
            { g.drawLine(900, ddd+10, 1100, ddd+10);
            ddd+=10;
            }
            
            cc=0;
            for(int zz=1;zz<y[3].length&&y[3][zz]!=null;zz++)
                {
                    if(y[3][zz].endsWith(")"))
                    {
                       cc++;
                        g.drawString(y[3][zz], 910, ddd+=20);
                    } 
                }
            if(cc==0)
                g.drawRect(900, 50, 200, ddd-50);    
            else
            g.drawRect(900, 50, 200, ddd-50+10);
            
            gap = vv[4][0]*30;
            fgap = mt[4][0]*30;
           cc=0;
            g.drawString(y[4][0],630,270);
            g.drawLine(550, 280, 750, 280);
            ddd=280;
            for(int zz=1;zz<y[4].length&&y[4][zz]!=null;zz++)
                {
                    if(!y[4][zz].endsWith(")"))
                    {
                        cc++;
                        g.drawString(y[4][zz], 560, ddd+=20);
                    } 
                }
            if(cc==0)
                g.drawLine(550, ddd, 750, ddd);
            else
            {g.drawLine(550, ddd+10, 750, ddd+10);
            ddd+=10;}
            cc=0;
        for(int zz=1;zz<y[4].length&&y[4][zz]!=null;zz++)
                {
                    if(y[4][zz].endsWith(")"))
                    {
                        cc++;
                        g.drawString(y[4][zz], 560, ddd+=20);
                    } 
                }
        if(cc==0)
            g.drawRect(550, 250, 200, ddd-250);    
            else
            g.drawRect(550, 250, 200, ddd-250+10);
            
        }*/
        
         /* ooo o1=new ooo();
          jDesktopPane1.add(o1);
          o1.setVisible(true);*/
       }
       catch(Exception e)
       {
           System.out.println(e);
           e.printStackTrace();
           JOptionPane.showMessageDialog(this, "ERROR OCCURED"+e);
           System.exit(0);
       }

           
              
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

         BufferedImage b1=null ;
        try

        {

                 Dimension  d1=Toolkit.getDefaultToolkit().getScreenSize();
                 Robot r1=new Robot();
                 b1=r1.createScreenCapture(new Rectangle(d1)) ;
                 JFileChooser jjjj=new JFileChooser();
                 FileFilter filter = new FileNameExtensionFilter("image file","jpg");
                 jjjj.setFileFilter(filter);
                 jjjj.showSaveDialog(new JTable());
                 File f1=jjjj.getSelectedFile();
                 String ssss=f1.getAbsolutePath();
                 ImageIO.write(b1,"jpg",new File(ssss));                     
}
          catch(Exception e){}      
 // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
   try {
    for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
           // UIManager.setLookAndFeel(info.getClassName());
            //UIManager.setLookAndFeel(“com.sun.java.swing.plaf.windows.WindowsLookAndFeel”);
          //  UIManager.setLookAndFeel(new SyntheticaStandardLookAndFeel());
           // UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
           UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            break;
        }
    }
} catch (Exception e) {
    // If Nimbus is not available, you can set the GUI to another look and feel.
}

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ok().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
